---
name: JSHead
description: Blogging about Web/Mobile Dev
meta_description: Blogging about Web/Mobile Dev
markdown: kramdown
highlighter: 
logo: false
paginate: 5
baseurl: "/"
domain_name: http://jshead.io
google_analytics: UA-XXXXXXXX-X
gems:
- jekyll-paginate
url: blog url
author: Kuba
